name: app_itopnc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  liquid_swipe: ^3.0.0
  lottie: ^2.2.0
  page_transition: ^2.0.9
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.5
  animated_splash_screen: ^1.3.0
  http: ^0.13.5
  webfeed: ^0.7.0
  xml2json: ^5.3.2
  connectivity_plus: ^2.1.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/onboard/
  - assets/images/slider/
  - assets/logo/
  - assets/detail/
  - assets/images/
  
